server:
  port: 8080
  servlet:
    context-path: /springboot

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  cache:
    type: redis
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secretKey: ${JWT_SECRET:defaultValueIfMissing}
  issuer: "springboot-service"
  audience: "web-client"
  expiration: 900000

cors:
  origins: ${CORS_ALLOWED_ORIGINS}
  methods: ${CORS_ALLOWED_METHODS}

cloudinary:
  url: "cloudinary://${CLOUDINARY_API_KEY}:${CLOUDINARY_SECRET_KEY}@${CLOUDINARY_CLOUD_NAME}"